name: cloud_project
description: A new Flutter project.


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.2
  # tflite: ^1.1.2
  # firebase_ml_custom: ^0.2.0+3
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.1
  cloud_firestore: ^4.0.4
  firebase_storage: ^11.0.4
  shared_preferences: ^2.0.15
  progress_dialog:
    git:
      url: https://github.com/mostafaAbdelazim/progress_dialog.git
  flutter_facebook_auth: ^5.0.6
  http: ^0.13.5
  image_picker: ^0.8.6
  cached_network_image: ^3.2.2
  smooth_page_indicator: ^1.0.0+2
  the_apple_sign_in: ^1.1.1
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  url_launcher: ^6.1.6
  file_picker: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^2.0.0





flutter:

  
  
  
  uses-material-design: true
  
  
  assets:
    - assets/images/
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
